### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Pawansingh333** [vanhbakaa/Coinsweeper#12]
Traceback (most recent call last):
  File "C:\Users\XYZ\Downloads\Coinsweeper-main\Coinsweeper-main\main.py", line 13, in <module>
    asyncio.run(main())
  File "C:\Users\XYZ\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\XYZ\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XYZ\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\XYZ\Downloads\Coinsweeper-main\Coinsweeper-main\main.py", line 8, in main
    await process()
  File "C:\Users\XYZ\Downloads\Coinsweeper-main\Coinsweeper-main\bot\utils\launcher.py", line 108, in process
    await run_tasks(tg_clients=tg_clients)
  File "C:\Users\XYZ\Downloads\Coinsweeper-main\Coinsweeper-main\bot\utils\launcher.py", line 163, in run_tasks
    await asyncio.gather(*tasks)
  File "C:\Users\XYZ\Downloads\Coinsweeper-main\Coinsweeper-main\bot\core\tapper.py", line 482, in run_tapper
    await Tapper(tg_client=tg_client).run(proxy=proxy)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Tapper.__init__() missing 1 required positional argument: 'multi_thread'

**Comment by jason866695** [comment]
author closed the option 'multi_thread',so you have to choose "Do you want to run the bot with multi-thread? (y/n) n".

**Comment by vanhbakaa** [comment]
Fixed
