### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by Aphotia1** [vanhbakaa/Coinsweeper#20]
Traceback (most recent call last):
  File "/home/yuqing/Coinsweeper/main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/home/yuqing/Coinsweeper/bot/utils/__init__.py", line 2, in <module>
    from . import launcher
  File "/home/yuqing/Coinsweeper/bot/utils/launcher.py", line 10, in <module>
    from bot.config import settings
  File "/home/yuqing/Coinsweeper/bot/config/__init__.py", line 1, in <module>
    from .config import settings
  File "/home/yuqing/Coinsweeper/bot/config/config.py", line 4, in <module>
    class Settings(BaseSettings):
  File "/home/yuqing/Coinsweeper/bot/config/config.py", line 8, in Settings
Which is API_HASH is undefined, also asks to edit .env file which i can't find

**Comment by vanhbakaa** [comment]
Copy it from .env-example then edit it
