### ISSUE TITLE
random time error: Unauthorized for Url

### ISSUE THREAD

**Issue by 0xTaaa** [vanhbakaa/Coinsweeper#6]
still getting this error
2024-09-29 06:16:48| WARNING | 441- main | Unknown error while trying to play game: 401 Client Error: Unauthorized for url: https://api.bybitcoinsweeper.com/api/games/start - Sleep 20s
Traceback (most recent call last):
File "/root/bybitcs-peter/bot/core/tapper.py", line 373, in run
  res.raise_for_status()
File "/root/bybitcs-peter/cs/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.bybitcoinsweeper.com/api/games/start

**Comment by vanhbakaa** [comment]
fixed

**Comment by 0xTaaa** [comment]
> fixed

still same

2024-09-29 07:19:38| WARNING | 446- main | Unknown error while trying to play game: 401 Client Error: Unauthorized for url: https://api.bybitcoinsweeper.com/api/games/start - Sleep 20s
Traceback (most recent call last):
File "/root/bybitcs-peter/bot/core/tapper.py", line 378, in run
  res.raise_for_status()
File "/root/bybitcs-peter/cs/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.bybitcoinsweeper.com/api/games/start

**Comment by vanhbakaa** [comment]
Install lastest version
