### ISSUE TITLE
ModuleNotFoundError: No module named 'better_proxy'

### ISSUE THREAD

**Issue by enzothea** [vanhbakaa/Coinsweeper#9]
Traceback (most recent call last):
  File "/root/bybit/main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/root/bybit/bot/utils/__init__.py", line 2, in <module>
    from . import launcher
  File "/root/bybit/bot/utils/launcher.py", line 8, in <module>
    from better_proxy import Proxy
ModuleNotFoundError: No module named 'better_proxy'

FIXED

**Comment by Darkcode2-cyber** [comment]
How did you fix it
